import { StyleSheet } from 'react-native';
import type { AppTheme } from '@/hooks/useAppTheme';

export function createMissionsStyles({ colors, surfaces }: AppTheme) {
  return StyleSheet.create({
    root: { flex: 1 },
    scroll: { flex: 1 },
    scrollContent: { paddingHorizontal: 18, paddingBottom: 120 },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 12,
    },
    title: {
      fontFamily: 'Fraunces_500Medium',
      fontSize: 42,
      fontWeight: '500',
      color: colors.ink,
      letterSpacing: -0.5,
    },
    addBtn: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 9999,
      backgroundColor: surfaces.ctaBg,
    },
    addBtnText: {
      fontSize: 12,
      fontWeight: '700',
      color: surfaces.ctaText,
      letterSpacing: 0.5,
    },
    tabs: { flexDirection: 'row', gap: 8, marginTop: 20, marginBottom: 4 },
    tabPill: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 9999,
      backgroundColor: surfaces.panelBg,
      borderWidth: 0.5,
      borderColor: surfaces.panelBorder,
    },
    tabPillActive: {
      backgroundColor: surfaces.ctaBg,
      borderColor: surfaces.ctaBg,
    },
    tabLabel: { fontSize: 13, fontWeight: '500', color: colors.inkSoft },
    tabLabelActive: { color: surfaces.ctaText, fontWeight: '600' },
    list: { gap: 10, marginTop: 8 },
    taskList: { gap: 10 },
    myTasksSection: { marginTop: 24 },
    myTasksLabel: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.inkFaint,
      letterSpacing: 1.6,
      marginBottom: 10,
    },
    emptyState: { padding: 20, alignItems: 'center' },
    emptyText: { fontSize: 13, color: colors.inkFaint },
    myTaskWrap: { marginBottom: 0 },
    myTaskCard: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 14,
      gap: 12,
    },
    taskInfoPressable: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    taskEmojiWrap: {
      width: 42,
      height: 42,
      borderRadius: 14,
      backgroundColor: surfaces.rowActive,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    taskEmoji: { fontSize: 22 },
    myTaskInfo: { flex: 1 },
    myTaskTitle: { fontSize: 15, fontWeight: '600', color: colors.ink },
    myTaskSub: { fontSize: 12, color: colors.inkSoft, marginTop: 1 },
    myTaskMemo: {
      fontSize: 11,
      color: colors.inkFaint,
      marginTop: 2,
      fontStyle: 'italic',
    },
    progressBg: {
      marginTop: 7,
      height: 4,
      borderRadius: 9999,
      backgroundColor: surfaces.chartTrack,
    },
    progressFill: {
      height: 4,
      borderRadius: 9999,
      backgroundColor: colors.pinkHot,
    },
    questReward: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.pinkText,
      marginTop: 4,
    },
    taskActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexShrink: 0,
    },
    myTaskStartBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.pinkHot,
      alignItems: 'center',
      justifyContent: 'center',
    },
    myTaskStartIcon: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.pinkText,
      marginLeft: 2,
    },
    deleteBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: surfaces.emojiCellBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
  });
}
