import { StyleSheet } from 'react-native';
import type { AppTheme } from '@/hooks/useAppTheme';

export type SettingsStyles = ReturnType<typeof createSettingsStyles>;

export function createSettingsStyles({ colors, surfaces }: AppTheme) {
  return StyleSheet.create({
    root: { flex: 1 },
    scroll: { flex: 1 },
    scrollContent: { paddingHorizontal: 18, paddingBottom: 80 },
    title: {
      fontFamily: 'Fraunces_500Medium',
      fontSize: 42,
      fontWeight: '500',
      color: colors.ink,
      marginTop: 8,
      letterSpacing: -0.5,
      marginBottom: 4,
    },
    section: { marginTop: 20 },
    sectionLabel: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.inkFaint,
      letterSpacing: 1.6,
      textTransform: 'uppercase',
      marginBottom: 8,
      paddingLeft: 4,
    },
    profileRow: {
      flexDirection: 'row',
      gap: 14,
      padding: 18,
      alignItems: 'flex-start',
    },
    avatar: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.pinkHot,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarImg: { width: 56, height: 56, borderRadius: 28 },
    avatarText: { color: '#fff', fontSize: 22, fontWeight: '700' },
    changePhoto: {
      fontSize: 10,
      color: colors.inkSoft,
      marginTop: 6,
      textAlign: 'center',
    },
    fieldLabel: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.inkFaint,
      marginBottom: 4,
    },
    nameInput: {
      fontSize: 16,
      fontWeight: '500',
      color: colors.ink,
      paddingVertical: 6,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: surfaces.dividerStrong,
    },
    saveBtn: {
      marginTop: 10,
      alignSelf: 'flex-start',
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 9999,
      backgroundColor: surfaces.ctaBg,
    },
    saveBtnDisabled: { opacity: 0.5 },
    saveBtnText: { fontSize: 12, fontWeight: '700', color: surfaces.ctaText },
    profileEmail: { fontSize: 12, color: colors.inkSoft, marginTop: 10 },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: surfaces.dividerStrong,
      marginHorizontal: 18,
    },
    toggleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 18,
      paddingVertical: 14,
      gap: 12,
    },
    aboutRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 18,
      paddingVertical: 14,
    },
    rowLabel: { fontSize: 15, fontWeight: '500', color: colors.ink },
    rowSub: { fontSize: 12, color: colors.inkSoft, marginTop: 2 },
    rowValue: { fontSize: 15, color: colors.inkSoft },
    logoutBtn: {
      marginTop: 28,
      height: 52,
      borderRadius: 9999,
      borderWidth: 1.5,
      borderColor: colors.error,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: surfaces.rowActive,
    },
    logoutText: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.error,
      letterSpacing: 0.3,
    },
  });
}
